version: '3.8'

services: 
  mysqldb:
    image: mysql:5.7
    restart: always
    build:
      context: ./mysqlDocker
      dockerfile: Dockerfile
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: clinic
    ports:
      - 3306:3306
    networks:
      - backendNetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: node-mysql-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - backendNetwork

networks:
  backendNetwork:

